
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edwinfinch
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleAndOutput = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        middleLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        outputLabel2 = new javax.swing.JLabel();
        revealPassword = new javax.swing.JButton();

        titleAndOutput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        titleAndOutput.setText("Pointless Password Program");

        usernameLabel.setText("Username");

        middleLabel.setText("Password");

        usernameInput.setToolTipText("");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });

        outputLabel2.setText("No password, yet.");

        revealPassword.setText("Reveal Password");
        revealPassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                revealPasswordStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleAndOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middleLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(passwordInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revealPassword)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleAndOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleLabel)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(revealPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    String monogram = "";
    
    private void throwError(String errorText){
        JOptionPane.showMessageDialog(null, errorText, "Error!", JOptionPane.ERROR_MESSAGE);
    }
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //Since we're dealing with passwords we need a char array for that
        char[] passwordChar = null;
        //String for username
        String username = null, password = null;
        
        //Get the according string from each input
        username = usernameInput.getText().toLowerCase();
        passwordChar = passwordInput.getPassword();
        
        //Make sure it's longer than 8 chars and if it isn't show an error
        if(passwordChar.length < 8){
            throwError("Password must be longer than 8 characters.");
            return;
        }
        
        //Set password to string, to lowercase, then add a number between 0-100 
        password = new String(passwordChar);
        password = password.toLowerCase();
        password = password + ((int)Math.floor(Math.random()*101));
        
        //Output it
        titleAndOutput.setText("Username: " + username);
        outputLabel2.setText(password);
        //Make sure password isn't showing by default.
        outputLabel2.setVisible(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void revealPasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_revealPasswordStateChanged
        outputLabel2.setVisible(true);
    }//GEN-LAST:event_revealPasswordStateChanged

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
    }//GEN-LAST:event_passwordInputActionPerformed

    static public void main(String arguments[]){
        //set up frame/window and launch it
        Main main = new Main();
        JFrame frame = new JFrame();
        frame.setSize(250, 250);
        frame.setContentPane(main);
        frame.setResizable(false);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel middleLabel;
    private javax.swing.JLabel outputLabel2;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton revealPassword;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleAndOutput;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
