package activity5.part3;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        newnum_button = new javax.swing.JButton();
        submit_button = new javax.swing.JButton();
        howclose_text = new javax.swing.JLabel();
        value_spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        title.setText("Random Guesser!");

        newnum_button.setText("New Number");
        newnum_button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newnum_buttonStateChanged(evt);
            }
        });
        newnum_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newnum_buttonActionPerformed(evt);
            }
        });

        submit_button.setText("Submit");
        submit_button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                submit_buttonStateChanged(evt);
            }
        });
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        howclose_text.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        howclose_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        howclose_text.setText("How close you are to display here...");

        value_spinner.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        value_spinner.setMaximumSize(new java.awt.Dimension(100, 100));
        value_spinner.setMinimumSize(new java.awt.Dimension(0, 0));
        value_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                value_spinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(howclose_text, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit_button)
                            .addComponent(value_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(newnum_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(42, 42, 42)
                .addComponent(howclose_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(value_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newnum_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final int[] limits = {
        100, 50, 25, 15, 10, 5, 4, 1
    };
    
    public final String[] temps = {
        "Poop", "Freezing", "Cold", "Cool", "Warm", "Hot", "Boiling"
    };
    
    public void refresh(){
        /*
        Freezing—more than 50 away.
        Cold—more than 25 away.
        Cool—more than 15 away.
        Warm—more than 10 away.
        Hot—more than 5 away.
        Boiling—between 1 and 4 away.
        */
        int difference = value-toGuess;
        if(difference < 0){
            difference = difference*(-1);
        }
        int i;
        for(i = 1; i != 8; i++){
            if(difference > limits[i] && difference < limits[i-1]){
                howclose_text.setText(temps[i-1]);
            }
            //System.out.println("i == " + i + "limits[i] " + limits[i]);
        }
    }
    
    int value = 0;
    int toGuess = 0;
    private void value_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_value_spinnerStateChanged
        value = (Integer)value_spinner.getValue();
    }//GEN-LAST:event_value_spinnerStateChanged

    public int random()
    {
        int min = 0;
        int max = 100;
        int range = (max - min) + 1;     
        return (int)(Math.random() * range) + min;
    }
    
    private void newnum_buttonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newnum_buttonStateChanged
        //need to delete this crap and it doesn't let me
    }//GEN-LAST:event_newnum_buttonStateChanged

    private void submit_buttonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_submit_buttonStateChanged

    }//GEN-LAST:event_submit_buttonStateChanged

    private void newnum_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newnum_buttonActionPerformed
        toGuess = random();
        System.out.println(toGuess);
    }//GEN-LAST:event_newnum_buttonActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        refresh();
        if(toGuess == value){
            howclose_text.setText("You got it: " + toGuess);
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel howclose_text;
    private javax.swing.JButton newnum_button;
    private javax.swing.JButton submit_button;
    private javax.swing.JLabel title;
    private javax.swing.JSpinner value_spinner;
    // End of variables declaration//GEN-END:variables
}
