/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edwin Finch
 */
public class DataCaptureGUI extends javax.swing.JFrame {

    /**
     * Creates new form DataCaptureGUI
     */
    public DataCaptureGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ver_text = new javax.swing.JLabel();
        name_text = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        submit_b = new javax.swing.JButton();
        title_text = new javax.swing.JLabel();
        not_my_first_t = new javax.swing.JLabel();
        quit_b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ver_text.setFont(new java.awt.Font("TI-83p Mini Sans", 0, 11)); // NOI18N
        ver_text.setText("DataCapture v. 0.3-b2");

        name_text.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        name_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_text.setText("Name:");

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });

        submit_b.setText("Submit");
        submit_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_bActionPerformed(evt);
            }
        });

        title_text.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        title_text.setText("Data Capture");

        not_my_first_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        not_my_first_t.setText("What's your name?");

        quit_b.setText("Quit");
        quit_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quit_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ver_text)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(not_my_first_t, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit_b))
                    .addComponent(title_text)
                    .addComponent(name_text))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(not_my_first_t)
                .addGap(30, 30, 30)
                .addComponent(name_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ver_text)
                    .addComponent(quit_b))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    public int stage = 0;
    
    public String get_reaction(String feeling){
        String returnvalue = new String("error 1");
        switch (feeling) {
            case "good":
            case "Good":
                returnvalue = "I'm good too :). Hope your day gets even gooder.";
                break;
            case "okay":
            case "Okay":
                returnvalue = "Well I hope your day goes better than okay :)";
                break;
            default:
                returnvalue = "Because I'm a computer I don't know that emotion :(";
                break;
        }
        return returnvalue;
    }
    
    private void submit_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_bActionPerformed
        // TODO add your handling code here:
        String input = new String("testpost");
        String name = new String("Edwin");
        input = name_tf.getText();
        
        if(stage == 0){
            name = input;
        }
        
        switch(stage){
            case 0:
                not_my_first_t.setText("Wussup, " + input + ". How's it going?");
                name_text.setText("Feeling:");
                break;
            case 1:
                not_my_first_t.setText(get_reaction(input));
                name_text.setText("Final words? ");
                break;
            case 2:
                not_my_first_t.setText("Well I've got to go, nice meeting you, " + name + "!");
                break;
        }
        stage++;
    }//GEN-LAST:event_submit_bActionPerformed

    private void quit_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_bActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quit_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataCaptureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataCaptureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataCaptureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataCaptureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataCaptureGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel name_text;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel not_my_first_t;
    private javax.swing.JButton quit_b;
    private javax.swing.JButton submit_b;
    private javax.swing.JLabel title_text;
    private javax.swing.JLabel ver_text;
    // End of variables declaration//GEN-END:variables
}
