
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edwinfinch
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleAndOutput = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        middleLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        firstInput = new javax.swing.JTextField();
        middleInput = new javax.swing.JTextField();
        lastInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        titleAndOutput.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        titleAndOutput.setText("Monogram Creator");

        firstLabel.setText("First name:");

        middleLabel.setText("Middle name:");

        lastLabel.setText("Last name:");

        firstInput.setToolTipText("");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(middleLabel)
                        .addGap(4, 4, 4)
                        .addComponent(middleInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleAndOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleAndOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabel)
                    .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleLabel)
                    .addComponent(middleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastLabel)
                    .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    String monogram = "";
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //simple array to keep track of all the input
        String[] inputs = {
            "Hello", "There", "World"
        };
        //Get the according substring from each input and set lower/uppercase accordingly
        inputs[0] = firstInput.getText().substring(0, 1).toLowerCase();
        inputs[2] = middleInput.getText().substring(0, 1).toLowerCase();
        inputs[1] = lastInput.getText().substring(0, 1).toUpperCase();
        
        //add them all to one string
        for(int i = 0; i < 3; i++){
            monogram = monogram + inputs[i];
        }
        //set it to a string
        titleAndOutput.setText(monogram);
    }//GEN-LAST:event_submitButtonActionPerformed

    static public void main(String arguments[]){
        //set up frame/window and launch it
        Main main = new Main();
        JFrame frame = new JFrame();
        frame.setSize(250, 200);
        frame.setContentPane(main);
        frame.setResizable(false);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstInput;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField lastInput;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JTextField middleInput;
    private javax.swing.JLabel middleLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleAndOutput;
    // End of variables declaration//GEN-END:variables
}
