
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edwinfinch
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        outputText = new javax.swing.JLabel();

        titleLabel.setFont(new java.awt.Font("Al Tarikh", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("CD Collection Thingy");

        inputText.setText("Title - Artist");
        inputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        outputText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputText.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputText)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton)
                    .addComponent(outputText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //static variables and whatnot for use
    static String inputTextValue = "Nothing, yet.";
    static ArrayList <String> collection = new ArrayList();
    static String[] preTitles = {
        "Blink 182 - Adam's Song", "C418 - Droopy Likes Ricochet", "Blink 182 - First Date",
        "Mozart - Some Song", "Hello - World"
    };
    
    static private void redraw(){
        //sort the collection.
        Collections.sort(collection);
        //clear the area 
        outputArea.setText("");
        //for every item, get the number and add a new row for it
        for(int i = 0; i < collection.size(); i++){
            if(i == 0){
                //but on 0 don't make a new row to prevent 1 blank row
                outputArea.setText(collection.get(0));
            }
            else{
                outputArea.setText(outputArea.getText() + "\n" + collection.get(i));
            }
        }
    }
    
    private void addItem(){
        //get the item
        inputTextValue = inputText.getText();
        //add it to the collection
        collection.add(inputTextValue);
        //tell user success, and redraw
        outputText.setText("Added: " + inputTextValue);
        redraw();
        //clear the input box because they're probably not going
        //to enter the same thing twice.
        inputText.setText("");
    }
    
    private void removeItem(){
        //get the text from the input
        inputTextValue = inputText.getText();
        //make sure it exists
        int result = Collections.binarySearch(collection, inputTextValue);
        System.out.println("Result: " + result);
        if(result > -1){
            //if it does, remove it
            collection.remove(inputTextValue);
            outputText.setText("Removed: " + inputTextValue);
        }
        else{
            //otherwise throw an error
            outputText.setText("There is no CD by that name/artist.");
        }
        //redraw the list
        redraw();
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //when add button clicked, add item in input
        addItem();
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        //when remove pressed, remove the item inputted
        removeItem();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void inputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextActionPerformed
        //when the enter key is pressed, add the item in the input
        addItem();
    }//GEN-LAST:event_inputTextActionPerformed

    static public void main(String arguingWithPeopleSucksSometimes[]){
        //set up frame/window and launch it
        Main main = new Main();
        JFrame frame = new JFrame();
        frame.setSize(425, 310);
        frame.setContentPane(main);
        frame.setResizable(false);
        frame.setVisible(true);
        //add the already made titles into the ArrayList
        for(int i = 0; i < 5; i++){
            collection.add(preTitles[i]);
        }
        //redraw
        redraw();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField inputText;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea outputArea;
    private javax.swing.JLabel outputText;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
